import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Navigation/Nav";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="apple-touch-icon" sizes="76x76" href="./img/apple-icon.png" />
        <link rel="icon" type="image/png" href="./img/favicon.png" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        />

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />

        <script src="https://kit.fontawesome.com/42d5adcbca.js" crossOrigin="anonymous"></script>


      </head>
      <body className="g-sidenav-show  bg-gray-100">
        <Toaster position="top-center" />

        <main className="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
          {children}

        </main>
        <script src="./js/soft-ui-dashboard.min.js?v=1.0.6"></script>
        <script async defer src="https://buttons.github.io/buttons.js"></script>
      </body>
    </html>

  );
}
